version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
cache: packages -> **\packages.config
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build --configuration Release
test_script:
- ps: >-
    dotnet restore --packages .\packages --verbosity m .\dataprocessor.tests\
- ps: >-
    .\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe `
        -register:user `
        -target:"nunit3-console.exe" `
        -targetargs:"-domain=single -result=TestResult.xml;format=AppVeyor dataprocessor.tests\bin\Release\net461\dataprocessor.tests.dll" `
        -output:".\coverage.xml" `
        -filter:"+[dataprocessor*]* -[dataprocessor.tests*]*"
- ps: >-
    nunit3-console.exe `
        -domain=single `
        "-result=TestResult2.xml;format=AppVeyor" `
        dataprocessor.benchmarks\bin\Release\net461\dataprocessor.benchmarks.exe
- ps: >-
    .\packages\Codecov\1.0.5\tools\codecov.exe -f coverage.xml
artifacts:
- path: dataprocessor.benchmarks/bin/Release/net461/BenchmarkDotNet.Artifacts/
  name: Benchmarks
- path: coverage/
  name: Coverage