version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
cache: packages -> **\packages.config
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test_script:
 - ps: >-
    .\run_coverage.ps1
    .\packages\Codecov.1.0.3\tools\codecov.exe -f coverage.xml
artifacts:
- path: dataprocessor.benchmarks/bin/Release/BenchmarkDotNet.Artifacts/
  name: Benchmarks
- path: coverage
  name: Coverage